## Day2 
### Numpy
- Introduction 
- Basics
- Indexing
- Random Methods

- Numerical Python
- Numpy is python library used to create arrays
    - 1D
    - 2D
    - Multi Dimentional
- Designed for mathmetical computation at easier and faster 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Mouni\AppData\Local\Continuum\anaconda3\python.exe -m pip install --upgrade pip' command.


In [2]:
# np is alias to numpy
import numpy as np

In [3]:
np.__version__

'1.16.4'

## Numpy Basics
### Create numpy arrays

In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
type(a)

numpy.ndarray

In [8]:
a.ndim

1

In [9]:
b = np.array([1,2,'a','b',3,4.0])
b

array(['1', '2', 'a', 'b', '3', '4.0'], dtype='<U11')

- b --> bool
- i --> signed int
- u --> unsigned int
- U --> Unicoded
- O --> Object
- f --> float

In [10]:
# 1D
a1D = np.array([1,2,3])
a1D

array([1, 2, 3])

In [11]:
# 2D
a2D = np.array([[1,2,3],[4,5,6]])
a2D

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a2D.ndim

2

In [13]:
# 3D
a3D = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])

In [14]:
a3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
a3D.ndim

3

### Accessing elements

In [17]:
a1D

array([1, 2, 3])

In [18]:
a1D[0]

1

In [19]:
a1D[-1]

3

In [20]:
a3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
a3D[1][1,1]

11

In [23]:
a3D[1,1,1]

11

In [24]:
a3D[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a3D[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [28]:
a3D[1][1,1]

11

In [31]:
a3D[1][:,1]

array([ 8, 11])

- Do more Slicing on multi dimentional array

In [33]:
a3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
a3D[1][:,1]

array([ 8, 11])

In [36]:
a3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
l1 = [1,2,3,4,5]
l1[:]

[1, 2, 3, 4, 5]

In [38]:
l1[::]

[1, 2, 3, 4, 5]

In [39]:
l1[::2]

[1, 3, 5]

### Attributes of NumPy to Inspect Structure
- shape : shape of array
- dtype : data type
- ndim : no of dimentions
- itemsize : Memory used by each element in bytes
- size : size of array

In [40]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [45]:
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.itemsize)
print(a.size)

(5,)
int32
1
4
5


In [46]:
a2D

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a2D.shape

(2, 3)

In [48]:
a2D.size

6

### other common ways to initialize arrays

- np.arange()
    - Creates array with incremnts of fixed step size

In [49]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(0,10,2)
# 0 --> start value
# 10 --> stop value
# 2 --> step size

array([0, 2, 4, 6, 8])

- np.ones()

In [53]:
np.ones(3)

array([1., 1., 1.])

In [54]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [56]:
np.ones((5,4),dtype = np.int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

- np.zeros()
    - try it

- np.linspace()

In [58]:
np.linspace(1,5)
# By default length = 50

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [59]:
np.linspace(1,20,5)
# 1 --> start
# 20 --> stop value
# 5 --> length

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

###  Random Method

In [62]:
np.random.random(5)# range between 0 to 1

array([0.85511739, 0.71253277, 0.67039832, 0.59565324, 0.68113754])

In [63]:
np.random.random([3,4])

array([[0.98091085, 0.22713502, 0.07788309, 0.95527252],
       [0.0634705 , 0.39277373, 0.4976235 , 0.67163902],
       [0.36229318, 0.59974264, 0.15477624, 0.99249591]])

In [66]:
np.random.randint(5)

4

In [70]:
np.random.randint(5,10)

7

In [77]:
np.random.randint(0,10,[3,4])

array([[4, 8, 6, 9],
       [6, 2, 6, 0],
       [0, 9, 6, 5]])